### ISSUE TITLE
stripListLeaders only strips one digit list leaders

### ISSUE THREAD

**Issue by paulbalomiri** [stiang/remove-markdown#10]
Hi,
this is a minor issue:

```
if (options.stripListLeaders) {
      output = output.replace(/^([\s\t]*)([\*\-\+]|\d\.)\s+/gm, '$1');
}
```

the regex should allow for multi-digit list leaders

```
10. tenth element
```

is not stripped at the moment.

On another note: would you care for a PR which also makes the regexps accessible from outer scopes for customization?

**Comment by Psychokrameur** [comment]
Somthing like `\d{0,10}`should do the trick ?

**Comment by paulbalomiri** [comment]
Yes, that would do the trick. Is there any reason not to use`\d+` ?

**Comment by stiang** [comment]
Should be fixed in master now.

**Comment by paulbalomiri** [comment]
Thx!
