### ISSUE TITLE
# in atx headers are removed, does not properly process terminal #s.

### ISSUE THREAD

**Issue by ThomasProctor** [stiang/remove-markdown#12]
Markdown allows `#`s within atx headers, as well as infinite trailing `#`s

Problem markdown: `# Header #1 ####################`.
Example gfm output:
# Header #1

remove-markdown output:
`Header 1 ####################`
Should be:
`Header #1`

**Comment by ThomasProctor** [comment]
I believe that replacing line 37, 

```
.replace(/^\#{1,6}\s*([^#]*)\s*(\#{1,6})?/gm, '$1')
```

with

```
.replace(/^\#{1,6}\s*(.*?)\s*(\#+\s*$)/gm, '$1')
.replace(/^\#{1,6}\s*/gm, '')
```

will do the trick. There might be a more elegant way to do this with a single regex, but treating headers with trailing `#`s separately seems like a logical way to do things to me. As a note, Jupyter's markdown allows for trailing white space after trailing `#`s in headers, and this deals with that as well.

**Comment by stiang** [comment]
This should be fixed in master.
