### ISSUE TITLE
Doesn't remove all availible horizontal rules

### ISSUE THREAD

**Issue by ThomasProctor** [stiang/remove-markdown#13]
John Gruber's markdown specs say:

> You can produce a horizontal rule tag `(<hr />)` by placing three or more hyphens, asterisks, or underscores on a line by themselves. If you wish, you may use spaces between the hyphens or asterisks.

Right now, remove-markdown only removes hyphens. It should remove all of these:

```
* * *

***

*****

- - -

---------------------------------------
```

Currently it will only remove the last one.

**Comment by ThomasProctor** [comment]
I think that removing line 40,

```
.replace(/^-{3,}\s*$/g, '')
```

and adding in

**Comment by ThomasProctor** [comment]
Misclick on the close button, sorry.

**Comment by Psychokrameur** [comment]
Hello Thomas, did you test your regex?
Doing what you suggest doesn't remove the example you gave... at least not completly

**Comment by ThomasProctor** [comment]
Yea, that makes sense. It's possible that I wrote that in python and didn't transcribe python's different syntax for multiline.

**Comment by ThomasProctor** [comment]
Actually, I submitted a pull request (#14) that has exactly what your suggestion.

**Comment by stiang** [comment]
Should be fixed in master.
