### ISSUE TITLE
Removes great than signs

### ISSUE THREAD

**Issue by wridgers** [stiang/remove-markdown#20]
Great than symbols are removed when they should not be.

```
> var rmd = require('remove-markdown');
undefined
> rmd('100 > 1')
'100  1'
> rmd('100 >= 1')
'100 = 1'
> rmd('1 < 100')
'1 < 100'
> rmd('1 <= 100')
'1 <= 100'
> 
```

**Comment by stiang** [comment]
Yes, looks like they are. I tried implementing a quick fix for this, but it broke something else. I have very little time for this project right now, so I would welcome a PR very much :)
