### ISSUE TITLE
Using alt-text of images & option to skip images

### ISSUE THREAD

**Issue by sambokai** [stiang/remove-markdown#30]
This should return "Google Search":

```javascript
removeMd("![Google Search](https://www.google.com/images/googlelogo.png)")
```

There should also be an option to skip images:

The following should then return "Welcome to our Website":

```javascript
removeMd("![Google Search](https://www.google.com/images/googlelogo.png) Welcome to our Website.")
```

Any thoughts?

**Comment by stiang** [comment]
Agreed. If you’re up for submitting a PR I’d gladly merge it!

**Comment by sambokai** [comment]
Sure. I can take a shot.
