### ISSUE TITLE
Option to configure the HTML tags to remove

### ISSUE THREAD

**Issue by GiridharanNarayanan** [stiang/remove-markdown#32]
Hi Stian,
     Currently this lib removes all the HTML tags in a string. We have a requirement where `<sub>` and `<sup>` makes sense and should not be removed. Is it possible to add that option? I am willing to get that change in a PR if you are convinced about the scenario.

**Comment by stiang** [comment]
Yes, that sounds like a nice addition, a PR would be welcome! I think the default should still be to remove all, and the option should probably take an array of tags to keep (unless you have a better/different suggestion).

I have no idea how difficult this would be to achieve, though. If it means we’ll have to add a full HTML parser it might be better solved in a different way - maybe some kind of plugin interface?

**Comment by GiridharanNarayanan** [comment]
I have created a PR with the same approach you suggested. Let me know if you are fine with the solution, I shall update the documentation and the tests too.
PR: #33

**Comment by stiang** [comment]
Hi, sorry for the super late reply (real-life stuff happened and I more or less stopped using node.js). I have now merged your PR and published 0.5.0 to npm. Please give it a spin if you are still using the library. Closing for now.
