### ISSUE TITLE
Removing links not working in several occasions

### ISSUE THREAD

**Issue by Abrynos** [stiang/remove-markdown#36]
i have a string of a changelog fetched from github-api which i get following line out of:
`[!] We've rewritten our **[IPC](https://github.com/JustArchi/ArchiSteamFarm/wiki/IPC)**`

in theory it should be 
`[!] We've rewritten our **https://github.com/JustArchi/ArchiSteamFarm/wiki/IPC**` when we remove markdown from it. sadly it becomes this: 
`!] We've rewritten our [IPC`

**Comment by codella** [comment]
On a similar note, there is an issue that strips underscores from the links:

![removeMarkdown](https://user-images.githubusercontent.com/4209616/54520515-2b65db00-4969-11e9-86e4-386482e205c5.png)
