### ISSUE TITLE
Emphasis chars are being removed incorrectly in some corner scenarios

### ISSUE THREAD

**Issue by vaibhav1192** [stiang/remove-markdown#39]
In some scenarios, emphasis chars are being removed, even though markdown renderers don't render them with emphasis.
Eg.
### Common for '#' and '*'
| Text     | Remove-Markdown | markdown renderer |   |   |
|----------|-----------------|---------------------|---|---|
| `*s****` | `s*`            | *s****              |   |   |
| `**s **` | `s`             | **s **              |   |   |
| `**_*`   | ``              | **_*                |   |   |
### Specific to '_'. 
| Text     | Remove-Markdown | markdown renderer |   |   |
|----------|-----------------|--------------------------|---|---|
| `a_s_d`  | `asd`           | a_s_d                    |   |   |
| `a _s_d` | `a sd`          | a _s_d                   |   |   |
| `a_s_ d` | `as d`          | a_s_ d                   |   |   |

And there is a slight difference between the way _ and * are rendered. Unlike *, _ works only if there is non word character before the opening _ tag and after closing _ tag. Though currently * _ are currently being handled with the same regex.

**Comment by vaibhav1192** [comment]
@stiang I have raised a PR #38 for handling these cases. Let me know if it makes sense or if you have any feedback.

**Comment by stiang** [comment]
Hi, sorry for the super late reply (real-life stuff happened and I more or less stopped using node.js). I have now merged your PR and published 0.5.0 to npm. Please give it a spin if you are still using the library. Closing for now.
