### ISSUE TITLE
Unexpected output when GFM tasklist item has inline link

### ISSUE THREAD

**Issue by mirka** [stiang/remove-markdown#42]
**Test case**

```
removeMarkdown('- [ ] my task [link](https://test.com)', {
      gfm: true,
      stripListLeaders: false,
  });
```

**What I wanted to happen**

```
- [ ] my task link
```

**What actually happened**

```
-  ] my task [link
```

**Version**
0.3.0

**Comment by stiang** [comment]
Hi, sorry for the super late reply (real-life stuff happened and I more or less stopped using node.js).

It looks like this is fixed in 0.5.0, which I just published to npm. Please give it a spin if you are still using the library. Closing for now.
