### ISSUE TITLE
PHP port if people are looking for it

### ISSUE THREAD

**Issue by tobsn** [stiang/remove-markdown#43]
https://gist.github.com/tobsn/188425fb6cbec4a9bdd9d0d3a82d3316

Hope it will help someone, and thank you @stiang for the code!

**Comment by KTamas** [comment]
damn I should have looked at the issues before I rolled my own lol! @stiang thanks for this library.

**Comment by stiang** [comment]
Nice, thanks for letting us know!

(Sorry for the super late reply (real-life stuff happened and I more or less stopped using node.js)).
