### ISSUE TITLE
SNYK Security Vulnerablity: ReDoS

### ISSUE THREAD

**Issue by staghouse** [stiang/remove-markdown#47]
See https://snyk.io/vuln/SNYK-JS-REMOVEMARKDOWN-73635

Summary:

Denial of Service (DoS) describes a family of attacks, all aimed at making a system inaccessible to its original and legitimate users. There are many types of DoS attacks, ranging from trying to clog the network pipes to the system by generating a large volume of traffic from many machines (a Distributed Denial of Service - DDoS - attack) to sending crafted requests that cause a system to crash or take a disproportional amount of time to process.

The Regular expression Denial of Service (ReDoS) is a type of Denial of Service attack. Regular expressions are incredibly powerful, but they aren't very intuitive and can ultimately end up making it easy for attackers to take your site down.

**Comment by davewichers** [comment]
Hey. Is development on this project active at all? If so, is this issue going to be addressed anytime soon?

**Comment by olessavluk** [comment]
duplicate of https://github.com/stiang/remove-markdown/issues/35
fixed by PR https://github.com/stiang/remove-markdown/pull/44

**Comment by davewichers** [comment]
While this issue is a duplicate of #35, the PR #44 doesn't actually fix this issue yet. See the discussion on #35 for more/current details.
