### ISSUE TITLE
Not stripping all markdown

### ISSUE THREAD

**Issue by bjarneo** [stiang/remove-markdown#48]
Case:

```js
const removeMarkdown = require('remove-markdown');
const markdown = 'This text entry should contain a link to [_**Github**_](https://www.github.com/). And this should **work** just _**fine**_.';

console.log(removeMarkdown(markdown))
// This text entry should contain a link to Github. And this should **work** just fine.
```

**Comment by stiang** [comment]
Hi, sorry for the super late reply (real-life stuff happened and I more or less stopped using node.js). 

This appears to have been fixed in 0.5.0, which I just published to npm. Please give it a spin if you are still using the library. Closing for now.
