### ISSUE TITLE
Add engines to package.json

### ISSUE THREAD

**Issue by MichaelDeBoey** [stiang/remove-markdown#50]

**Comment by stiang** [comment]
Hi, sorry for the super late reply (real-life stuff happened and I more or less stopped using node.js). 

I guess we could add that, but I honestly don’t know which versions (if any) it doesn’t work on, so unless you have some specific information about what should be put in the `engines` field I’m inclined to leave it unset.

**Comment by MichaelDeBoey** [comment]
@stiang You could maybe use the latest tested version(s)?

**Comment by stiang** [comment]
@MichaelDeBoey Yes, but my understanding of the `engines` field is that I would then be saying that it _doesn’t work_ with other versions than the ones I test with. This could very well be untrue and would artificially limit the range of versions the package would be used with. 

I would be happy to add/update the field when I have concrete information about unsupported versions, but until then I’m leaving it unspecified

I’ll close this issue now, but feel free to continue to make the case for adding the `engines` field here, I’m still open to the possibility that there’s something I don’t understand about this.

**Comment by MichaelDeBoey** [comment]
So how could you be certain that it works with other versions if you're not testing against them?

**Comment by MichaelDeBoey** [comment]
For me (and how I've seen it being used in the OSS world) it means "These are the supported versions. Other versions _could_ work as well, but aren't actively supported, so we won't fix bugs for other versions than in this list"
