### ISSUE TITLE
Escaped characters are not removed

### ISSUE THREAD

**Issue by igr** [stiang/remove-markdown#58]
The following markdown:

```markdown
\# First  _paragraph_.
```

results with

```
\# First paragraph
```

and should be:

```
# First paragraph
```

**Comment by zuchka** [comment]
@igr [this PR](https://github.com/stiang/remove-markdown/pull/57) appears to have resolved this bug. I've added another test for checking escaped markdown. We'll need to cut a new release before the fix gets published to NPM. Thanks again for reporting this.
