### ISSUE TITLE
triple back tick

### ISSUE THREAD

**Issue by soomtong** [stiang/remove-markdown#8]
I've tested this 0.1.0 and before. maybe it doesn't remove triple back tick.
```
```javascript -> ` 
```
remain one back tick here, can u check this :)
thank you this nice package

**Comment by phun-ky** [comment]
It's a bit, weird, if you pull out the replace methods and do a test like this:

    '```test```'
      .replace(/\n={2,}/g, '\n')
      // Strikethrough
      .replace(/~~/g, '')
      // Fenced codeblocks
      .replace(/`{3}.*\n/g, '')
      .replace(/<(.*?)>/g, '$1')
      // Remove setext-style headers
      .replace(/^[=\-]{2,}\s*$/g, '')
      // Remove footnotes?
      .replace(/\[\^.+?\](\: .*?$)?/g, '')
      .replace(/\s{0,2}\[.*?\]: .*?$/g, '')
      // Remove images
      .replace(/\!\[.*?\][\[\(].*?[\]\)]/g, '')
      // Remove inline links
      .replace(/\[(.*?)\][\[\(].*?[\]\)]/g, '$1')
      // Remove Blockquotes
      .replace(/>/g, '')
      // Remove reference-style links?
      .replace(/^\s{1,2}\[(.*?)\]: (\S+)( ".*?")?\s*$/g, '')
      // Remove atx-style headers
      .replace(/^\#{1,6}\s*([^#]*)\s*(\#{1,6})?/gm, '$1')
      .replace(/([\*_]{1,3})(\S.*?\S)\1/g, '$2')
      .replace(/(`{3,})(.*?)\1/gm, '$2')
      .replace(/^-{3,}\s*$/g, '')
      .replace(/`(.+?)`/g, '$1')
      .replace(/\n{2,}/g, '\n\n');

You will get the expected result: `test`

**Comment by soomtong** [comment]
ooops!!! i m sorry, i didn't catch out the options `gfm` 
it's cool already :+1: 

thanks!
